---
- name: Create an HTML site with a cat image
  hosts: localhost
  gather_facts: no
  vars:
    cat_image_url: https://www.example.com/cat.jpg

  tasks:
    - name: wygeneruj dokument
      template:
        src: konfiguracja.txt
        dest: /var/www/konfiguracja.txt
