---
- name: generuj dokument
  hosts: localhost
  gather_facts: no
  vars:
    cat_image_url: https://www.example.com/cat.jpg
    zmienne:
      jakas_zmienna: 'jakas_wartosc_1234'

  tasks:
    - name: wygeneruj dokument
      template:
        src: dokument.txt
        dest: /tmp/kompletny_dokument.txt
