---
- name: Create an HTML site with a cat image
  hosts: localhost
  gather_facts: no
  vars:
    cat_image_url: https://www.example.com/cat.jpg

  tasks:
    - name: wygeneruj dokument
      template:
        src: dokument.txt
        dest: /tmp/kompletny_dokument.txt
