---
- name: Create an HTML site with a cat image
  hosts: localhost
  gather_facts: no
  vars:
    cat_image_url: https://www.example.com/cat.jpg

  tasks:
    - name: Create the HTML file
      template:
        src: index.html.j2
        dest: /var/www/html/index.html

    - name: Start the web server
      command: python3 -m http.server 8080 &
      become: yes

