- hosts: localhost

  vars_files:
    - jakies_zmienne.yml
    - "{{ srodowisko }}.yml" 
    - "{{ srodowisko }}_vault.yml" 

  tasks:

    - name: sprawdz srodowisko wykonujac modul ping
      ping:

    - name: wypisz haslo do bazy
      debug:
        msg: "{{ haslo_do_bazy }}"

    - name: doladuj zmienne
      include_vars:
        path: zmienn_kolejne.yml

